runtime: python27
api_version: 1
threadsafe: true
handlers:
- url: /
  static_files: mapev/index.html
  upload: mapev/index.html
- url: /login
  static_files: mapev/index.html
  upload: mapev/index.html
- url: /registerinterest
  static_files: mapev/index.html
  upload: mapev/index.html
- url: /signup
  static_files: mapev/index.html
  upload: mapev/index.html
- url: /response-reset-password/.*
  static_files: mapev/index.html
  upload: mapev/index.html
- url: /home
  static_files: mapev/index.html
  upload: mapev/index.html
- url: /
  static_dir: mapev
